<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Harsh-PC" ignored="0" name="FirstTest" tests="2" failures="1" timestamp="04 Jun 2017 15:33:12 GMT" time="138.784" errors="0">
  <testcase name="duplicateId" time="73.719" classname="FisrtSuite.DuplicateId">
    <failure type="java.lang.AssertionError" message="expected [0] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [5]
	at FisrtSuite.DuplicateId.duplicateId(DuplicateId.java:102)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- duplicateId -->
  <testcase name="Detailed" time="64.991" classname="FisrtSuite.DetailedLinkReport"/>
</testsuite> <!-- FirstTest -->
